language: go
go:
    - 1.5.1
before_script:
    - echo "do not call 'go get' please"
install:
    - export GOPATH=$GOPATH:`pwd`
script:
    - cd src/02-pass
    - cp -f main.go.sol1 main.go && go test -v -cover
    - cp -f main.go.sol2 main.go && go test -v -cover
    - cp -f main.go.sol3 main.go && go test -v -cover
    - cd ../03-json
    - cp -f main.go.sol1 main.go && go test -v -cover
    - cp -f main.go.sol2 main.go && go test -v -cover
    - cp -f main.go.sol3 main.go && go test -v -cover
    - cd ../04-interface
    - cp -f main.go.sol main.go && go test -v -cover
    - cd ../05-web
    - cp -f main.go.sol main.go && go test -v -cover
    - cd ../06-io
    - cp -f main.go.sol main.go && go test -v -cover
